Zoey_Completed css-brochure-form
Zoey1318/mod1-0822-code-solutions pull request #15
Opened 2022-09-01 23:58 UTC by Zoey1318

![css-brochure-form practice](https://user-images.githubusercontent.com/111097580/188031713-489f7ecc-7922-4c86-ba5b-898850536d10.jpg)

2022-09-02 21:08 UTC, scrumptiousdev requested changes
Overall looks like it's coming together but we still need some fixes here and there.

Also along with change requests, let's fix the overflowing issue when we resize the browser to a smaller width.
![Screenshot 2022-09-02 at 2 03 14 PM](https://user-images.githubusercontent.com/9010389/188235442-bf5bf069-4d58-49ae-a9a7-00eeaba8f2c3.png)

2022-09-02 21:08 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +input::placeholder {
Let's move all these stylings to `input` because in that way when user starts to type something then they can get the same styling like font family, font weight, size and padding
![Screenshot 2022-09-02 at 1 48 01 PM](https://user-images.githubusercontent.com/9010389/188234484-5e9b6d40-7678-43bf-a596-6ec950e582c9.png)

2022-09-02 21:08 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +}
If we remove `<legend>` from HTML then we won't need to hide anything

2022-09-02 21:08 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +}
By default, `input` is an `inline-block` element so we don't need to apply this to either of those

2022-09-02 21:08 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +  margin-left: 420px;
Two things here:
1. Let's try without setting width and height to button — generally it's good idea to not have fixed width and height to button. It's because we want it to stay flexible with any length of text to go into button. Try something like `<button class="submit">BUTTON WITH LONG TEXT</button>` and you will see how the text gets cut off
2. When we align things to the right side or moving any direction, we don't want to use `margin`. You can either use `text-align` or flexbox technique! :)

2022-09-03 02:50 UTC, Zoey1318 commented
![css-brochure-form practice 2](https://user-images.githubusercontent.com/111097580/188253033-572b4a3f-516e-450c-a805-f777408abede.jpg)

2022-09-04 15:39 UTC, scrumptiousdev requested changes
> Overall looks like it's coming together but we still need some fixes here and there.
> 
> Also along with change requests, let's fix the overflowing issue when we resize the browser to a smaller width. ![Screenshot 2022-09-02 at 2 03 14 PM](https://user-images.githubusercontent.com/9010389/188235442-bf5bf069-4d58-49ae-a9a7-00eeaba8f2c3.png)

I think you forgot to address this one :)
Plus, since button is now without width and height, how do we enlarge it like we have in the example from instructions?

2022-09-06 00:18 UTC, Zoey1318 commented
![css-brochure-form practice 3](https://user-images.githubusercontent.com/111097580/188522970-e789d0a8-cda4-4510-8805-23c353a87ff8.jpg)

2022-09-06 17:10 UTC, scrumptiousdev approved these changes
🪄 Approved! Great job!

2022-09-07 01:28 UTC, merged