Zoey_Completed css-layout-classes
Zoey1318/mod1-0822-code-solutions pull request #17
Opened 2022-09-03 02:13 UTC by Zoey1318

![css-layout-classes practice](https://user-images.githubusercontent.com/111097580/188251973-f4000478-8717-4577-adc3-3a4582210273.jpg)

2022-09-04 15:45 UTC, scrumptiousdev requested changes
Nicely done! Just one super tiny change request!

2022-09-04 15:45 UTC, scrumptiousdev commented on css-layout-classes/index.html
> +      <div class="column-full">
Are we missing `.column-full` styling in CSS?

2022-09-06 00:27 UTC, Zoey1318 commented
![css-layout-classes practice2](https://user-images.githubusercontent.com/111097580/188523456-5964cfe1-0182-4ab8-9ccf-95374276ae6b.jpg)

2022-09-06 17:17 UTC, scrumptiousdev approved these changes
🪄 Approved!

2022-09-07 01:28 UTC, merged