Zoey_Completed javascript-loops
Zoey1318/mod1-0822-code-solutions pull request #33
Opened 2022-09-23 05:42 UTC by Zoey1318

![javascript-loops-assignment](https://user-images.githubusercontent.com/111097580/191898274-984df5d5-1c4e-4d2d-9aac-8b429602f304.jpg)

2022-09-23 06:57 UTC, scrumptiousdev requested changes

2022-09-23 06:57 UTC, scrumptiousdev commented on javascript-loops/main.js
> +}
If you call this function with `repeatWord('hi', 3)` it only repeat 2 times.

2022-09-26 03:04 UTC, Zoey1318 commented
![javascript-loops practice_edit](https://user-images.githubusercontent.com/111097580/192185847-cd5fd341-14a9-4f32-9a75-684b31105136.jpg)

2022-09-26 17:51 UTC, scrumptiousdev approved these changes
🪄 Approved!

2022-09-27 02:55 UTC, merged