Zoey_Completed javascript-loops-practice
Zoey1318/mod1-0822-code-solutions pull request #34
Opened 2022-09-26 07:08 UTC by Zoey1318

![javascript-loops-pr](https://user-images.githubusercontent.com/111097580/192214328-8216e596-536f-4099-8842-7117e48b9b6e.png)

2022-09-26 17:57 UTC, scrumptiousdev requested changes

2022-09-26 17:57 UTC, scrumptiousdev commented on javascript-loops-practice/filter-out-nulls.js
> +}
I know this wasn't in the testing suite but let's see if we can fix this issue. This function is also filtering out `undefined`. Since `undefined` is not `null`, let's fix it so that it doesn't filter out `undefined`.

For example:
```
filterOutNulls([null, 1, undefined]); 
```
This should return `[1, undefined]` instead of `[1]`

2022-09-27 06:55 UTC, Zoey1318 commented on javascript-loops-practice/filter-out-nulls.js
> +}
used 'strictly not equal operator' this time!

2022-09-27 06:55 UTC, Zoey1318 commented
![loop practice revise](https://user-images.githubusercontent.com/111097580/192454491-c4ebce49-b644-4340-9ca5-47de3ec02f05.JPG)

2022-09-27 18:18 UTC, scrumptiousdev approved these changes
🪄 Approved!

2022-09-27 18:18 UTC, scrumptiousdev commented on javascript-loops-practice/filter-out-nulls.js
> +}
Way to go! 👍🏼

2022-09-28 02:42 UTC, merged