Zoey_Completed css-transitions
Zoey1318/mod1-0822-code-solutions pull request #42
Opened 2022-10-06 03:47 UTC by Zoey1318

![css-transitions pr](https://user-images.githubusercontent.com/111097580/194209755-4d1efa73-1539-48bf-85b1-fa106ea71afc.gif)

2022-10-06 21:45 UTC, scrumptiousdev requested changes

2022-10-06 21:45 UTC, scrumptiousdev commented on css-transitions/styles.css
> +  transition-delay: 0.5s;
This will "pop" the button color change after delay of 0.5 second instead of smooth animation. We need different property than `transition-delay`.

2022-10-06 21:45 UTC, scrumptiousdev commented on css-transitions/styles.css
> +  transition-delay: 0.5s;
This will "pop" the card out after delay of 0.5 second. We need different property than `transition-delay`.

2022-10-07 00:57 UTC, Zoey1318 commented
![css-transitions pr_edit](https://user-images.githubusercontent.com/111097580/194444168-799af412-da30-4a0e-be3a-73445f11b188.gif)

2022-10-07 01:09 UTC, scrumptiousdev approved these changes
🪄 Approved!

2022-10-08 03:50 UTC, merged