Zoey_Completed html-forms
Zoey1318/mod1-0822-code-solutions pull request #7
Opened 2022-08-28 22:29 UTC by Zoey1318

![html-forms practice](https://user-images.githubusercontent.com/111097580/187097086-9d9c3d45-8a46-4d3c-9b2d-e35516f8115b.gif)

2022-08-28 23:43 UTC, scrumptiousdev requested changes
Good job overall! One small change!

2022-08-28 23:43 UTC, scrumptiousdev commented on html-forms/index.html
> +      <label for="comments">
When we don't wrap the input control with `label` we need to connect those two with `for` and which one??

2022-08-29 00:05 UTC, Zoey1318 commented on html-forms/index.html
> +      <label for="comments">
input id? so for line 49 since there is no input do i need use textarea id="comments"?

2022-08-30 00:15 UTC, scrumptiousdev commented on html-forms/index.html
> +      <label for="comments">
Yes indeed!

2022-08-30 01:18 UTC, Zoey1318 commented
![recommit_html-forms](https://user-images.githubusercontent.com/111097580/187326592-5362af9f-8fec-4d2a-a890-431d17a7c8a1.jpg)

2022-08-30 01:21 UTC, scrumptiousdev approved these changes
🪄 Approved!

2022-08-30 01:22 UTC, merged