Zoey_Completed html-web-page
Zoey1318/mod1-0822-code-solutions pull request #9
Opened 2022-08-29 00:53 UTC by Zoey1318

![html-web-page practice](https://user-images.githubusercontent.com/111097580/187102997-181e97db-87e3-4aac-8a20-8ce0f2d32566.jpg)

2022-08-29 06:36 UTC, scrumptiousdev requested changes
Overall great job! We just need to clean up few things!

2022-08-29 06:36 UTC, scrumptiousdev commented on html-web-page/index.html
> +    <input type="text" id="yourname" name="username" placeholder="Your Name">
We are using `placeholder` in place of `label` so we don't necessarily have to have `label` and `id` for this one

2022-08-29 06:36 UTC, scrumptiousdev commented on html-web-page/index.html
> +    <select name="selectplan" id="select-plan">
Same goes here too. `label` is not needed hence no need for `id` as well

2022-08-30 00:12 UTC, Zoey1318 commented
![recommit_html-web-page](https://user-images.githubusercontent.com/111097580/187320346-5ec611da-39fd-41d9-95db-6731757c14fa.jpg)

2022-08-30 00:15 UTC, scrumptiousdev approved these changes
🪄 Approved!

2022-08-30 01:22 UTC, merged